name: Release a CV

on:
  push:
    tags:
      - "*" # Any tag pushed to the repository
      
permissions:
  contents: write
  
jobs:
  call_rendercv_workflow:
    name: RenderCV
    uses: ./.github/workflows/rendercv.yaml

  build:
    needs: call_rendercv_workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            *_CV.pdf
            *_CV.tex
          generate_release_notes: true
          make_latest: true
