name: Render a CV

on:
  push:
    branches:
      - main
  workflow_call: # to make the workflow triggerable from other workflows (release.yaml)

permissions:
  contents: write

jobs:
  rendercv:
    name: RenderCV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pyenv
        uses: "gabrielfalcao/pyenv-action@v18"
      - name: Create and activate virtualenv
        run: |
          pyenv install 3.13.1
          pyenv local 3.13.1
          python -m venv .cv
          source .cv/bin/activate
      - name: Install RenderCV
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Install pdflatex with biber
        run: |
          sudo apt-get install texlive-latex-base texlive-latex-extra texlive-latex-recommended texlive-bibtex-extra texlive-fonts-extra biber -y
      - name: Create docs folder
        run: mkdir -p docs
      - name: Build CV
        run: |
          cd src
          cv_file=$(find .  -maxdepth 1 -type f -name "*_CV.yaml" | head -n 1)
          if [ -z "$cv_file" ]; then
            echo "No RenderCV file found!"
            exit 1
          fi
          cd ..
          make project/build_all
      - name: Upload rendercv_output as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: RenderCV Output
          path: rendercv_output
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          base: HEAD
          filters: |
            cv:
              - '*.tex'
              - '*.html'
              - '*.pdf'
              - '*.md'
              - 'docs/*.md'
              - 'application_letters/*.pdf'
      - name: Push the changes
        if: steps.changes.outputs.cv == 'true'
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add -A
          git commit -m "render the latest CV"
          git push origin HEAD:main
