name: Update Bibliography

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  update-biblio:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Update bibliometrics
        run: python src/updatebibliometrics.py

      - name: Trigger rendercv workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}  # PAT required for workflow-to-workflow communication
          event-type: bibliography-updated