name: Update Bibliography

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-biblio:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run parsebib
        run: python src/parsebib.py

      - name: Check for changes
        id: check_changes
        run: |
          if ! git diff --quiet HEAD -- src/bibliography/; then
            echo "changes_found=true" >> $GITHUB_OUTPUT
          else
            echo "changes_found=false" >> $GITHUB_OUTPUT
          fi

      - name: Trigger rendercv workflow
        if: steps.check_changes.outputs.changes_found == 'true'
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}  # PAT required for workflow-to-workflow communication
          event-type: bibliography-updated